import type { Locale } from '@/lib/i18n';

const es = {
  nav: 'Duelos',
  title: 'Duelos Ranked',
  intro: 'Una consigna. Dos escritores. Una nueva oportunidad de subir de liga.',
  rulePrompt: 'La misma consigna',
  rulePromptBody: 'Tú y tu rival escriben a partir de la misma idea.',
  ruleTime: 'Cinco minutos para escribir',
  ruleTimeBody: 'El tiempo empieza cuando se encuentra un rival. Tu relato se envía al terminar.',
  ruleResult: 'Un veredicto para crecer',
  ruleResultBody: 'El juez evalúa ambos relatos. El resultado cuenta para tu liga.',
  start: 'Buscar rival',
  waiting: 'Buscando rival…',
  waitingBody: 'Mantén esta página abierta mientras encontramos a otro escritor.',
  lowActivity: 'Hay poca actividad ahora',
  lowActivityBody: 'Puedes seguir buscando o escribir ahora y esperar a que otro escritor responda después.',
  async: 'Escribir y esperar rival',
  cancel: 'Cancelar búsqueda',
  prompt: 'Consigna',
  editor: 'Tu relato',
  placeholder: 'La primera frase te espera…',
  remaining: 'Tiempo restante',
  submit: 'Enviar relato',
  submitting: 'Enviando…',
  minimum: 'Mínimo: 50 caracteres sin espacios.',
  limits: 'Límite del servidor',
  bytes: 'bytes UTF-8',
  characters: 'caracteres',
  saved: 'El texto se guarda en este navegador.',
  saveFailed: 'No se pudo guardar el texto en este navegador. Copia tu relato antes de salir.',
  frozen: 'Estamos comprobando el envío. Puedes reintentar con el mismo texto.',
  pending: 'Tu relato ya está enviado',
  pendingBody: 'Esperamos al rival y al veredicto. Puedes volver desde tu historial sin enviar otra vez.',
  queued: 'Tu Ranked está en espera',
  queuedBody: 'Otro escritor responderá a la misma consigna. El duelo y su resultado aparecerán en tu historial cuando haya un rival.',
  history: 'Historial de duelos',
  empty: 'Todavía no hay duelos',
  emptyBody: 'Tus partidas aparecerán aquí.',
  historyError: 'No se pudo cargar el historial.',
  retry: 'Reintentar',
  more: 'Ver más duelos',
  detail: 'Ver duelo completo',
  private: 'Detalle privado',
  rival: 'Rival por confirmar',
  won: 'Victoria',
  lost: 'Derrota',
  draw: 'Empate',
  in_progress: 'En progreso',
  abandoned: 'Abandonado',
  completed: 'Completado',
  all: 'Todos',
  ranked: 'Ranked',
  asyncRanked: 'Ranked asíncrono',
  practice: 'Práctica',
  sprint: 'Solo Sprint',
  challenge: 'Reto',
  result: 'Resultado del duelo',
  verdict: 'Veredicto',
  feedback: 'Para tu escritura',
  winner: 'Ganador',
  score: 'Puntuación',
  profile: 'Volver al perfil',
  another: 'Volver a Ranked',
  detailError: 'Este duelo todavía no está disponible o no tienes acceso.',
  forfeit: 'Rendirme',
  forfeitTitle: '¿Abandonar el duelo?',
  forfeitBody: 'Se contará como una derrota. Puedes perder puntos de liga y la tinta utilizada no se devuelve.',
  keepWriting: 'Seguir escribiendo',
  expired: 'El tiempo de escritura terminó',
  expiredBody: 'Conservamos el texto que quedó en este navegador. Puedes copiarlo antes de continuar.',
  unavailable: 'La escritura ya no está activa',
  unavailableBody: 'Revisa el historial para comprobar si el duelo se resolvió. Conservamos el texto de este navegador.',
  cancelled: 'La búsqueda terminó',
  finished: 'El veredicto está listo',
  viewResult: 'Ver resultado',
  otherMode: 'Ya tienes otra partida en curso',
  otherModeBody: 'Continúa esa partida en la aplicación antes de iniciar Ranked.',
  verification: 'Verifica tu correo para jugar Ranked.',
  sendVerification: 'Enviar correo de verificación',
  verificationSent: 'Correo enviado. Después de verificarlo, vuelve a intentar.',
  energy: 'Tinta disponible',
  cost: 'Coste por duelo',
  refill: 'Próxima recarga',
  noEnergy: 'No tienes tinta suficiente. Espera la próxima recarga.',
  queueList: 'Ranked pendientes',
  matched: 'Rival encontrado',
  expires: 'Disponible hasta',
  loading: 'Cargando duelos…',
};
type Copy = { [K in keyof typeof es]: string };
const en: Copy = {
  nav: 'Duels',
  title: 'Ranked duels',
  intro: 'One prompt. Two writers. A new chance to climb the leagues.',
  rulePrompt: 'The same prompt',
  rulePromptBody: 'You and your opponent write from the same idea.',
  ruleTime: 'Five minutes to write',
  ruleTimeBody: 'Time starts when an opponent is found. Your story is sent when time runs out.',
  ruleResult: 'A verdict to grow',
  ruleResultBody: 'The judge evaluates both stories. The result counts toward your league.',
  start: 'Find opponent',
  waiting: 'Finding an opponent…',
  waitingBody: 'Keep this page open while we find another writer.',
  lowActivity: 'It is quiet right now',
  lowActivityBody: 'Keep searching, or write now and wait for another writer to respond later.',
  async: 'Write and wait for an opponent',
  cancel: 'Cancel search',
  prompt: 'Prompt',
  editor: 'Your story',
  placeholder: 'Your first sentence awaits…',
  remaining: 'Time remaining',
  submit: 'Send story',
  submitting: 'Sending…',
  minimum: 'Minimum: 50 non-whitespace characters.',
  limits: 'Server limit',
  bytes: 'UTF-8 bytes',
  characters: 'characters',
  saved: 'Your text is saved in this browser.',
  saveFailed: 'Your text could not be saved in this browser. Copy your story before leaving.',
  frozen: 'Checking your submission. You can retry with the same text.',
  pending: 'Your story has been sent',
  pendingBody: 'Waiting for your opponent and the verdict. Return from your history without sending again.',
  queued: 'Your Ranked is waiting',
  queuedBody: 'Another writer will respond to the same prompt. The duel and result will appear in your history once there is an opponent.',
  history: 'Duel history',
  empty: 'No duels yet',
  emptyBody: 'Your matches will appear here.',
  historyError: 'Could not load duel history.',
  retry: 'Retry',
  more: 'Load more duels',
  detail: 'View full duel',
  private: 'Private detail',
  rival: 'Opponent to be confirmed',
  won: 'Victory',
  lost: 'Defeat',
  draw: 'Draw',
  in_progress: 'In progress',
  abandoned: 'Abandoned',
  completed: 'Completed',
  all: 'All',
  ranked: 'Ranked',
  asyncRanked: 'Async Ranked',
  practice: 'Practice',
  sprint: 'Solo Sprint',
  challenge: 'Challenge',
  result: 'Duel result',
  verdict: 'Verdict',
  feedback: 'For your writing',
  winner: 'Winner',
  score: 'Score',
  profile: 'Back to profile',
  another: 'Back to Ranked',
  detailError: 'This duel is not available yet or you do not have access.',
  forfeit: 'Forfeit',
  forfeitTitle: 'Leave the duel?',
  forfeitBody: 'This counts as a defeat. You may lose league points and spent ink is not refunded.',
  keepWriting: 'Keep writing',
  expired: 'Writing time is over',
  expiredBody: 'We kept the text left in this browser. Copy it before continuing.',
  unavailable: 'This writing session is no longer active',
  unavailableBody: 'Check your history to see whether the duel resolved. We kept the text from this browser.',
  cancelled: 'The search ended',
  finished: 'The verdict is ready',
  viewResult: 'View result',
  otherMode: 'You already have another match in progress',
  otherModeBody: 'Continue that match in the app before starting Ranked.',
  verification: 'Verify your email to play Ranked.',
  sendVerification: 'Send verification email',
  verificationSent: 'Email sent. Once verified, try again.',
  energy: 'Available ink',
  cost: 'Cost per duel',
  refill: 'Next refill',
  noEnergy: 'Not enough ink. Wait for the next refill.',
  queueList: 'Pending Ranked',
  matched: 'Opponent found',
  expires: 'Available until',
  loading: 'Loading duels…',
};
const pt: Copy = {
  nav: 'Duelos',
  title: 'Duelos Ranked',
  intro: 'Um tema. Dois escritores. Uma nova oportunidade de subir de liga.',
  rulePrompt: 'O mesmo tema',
  rulePromptBody: 'Você e seu rival escrevem a partir da mesma ideia.',
  ruleTime: 'Cinco minutos para escrever',
  ruleTimeBody: 'O tempo começa quando um rival é encontrado. Seu relato é enviado ao terminar.',
  ruleResult: 'Um veredito para crescer',
  ruleResultBody: 'O juiz avalia os dois relatos. O resultado conta para sua liga.',
  start: 'Buscar rival',
  waiting: 'Buscando rival…',
  waitingBody: 'Mantenha esta página aberta enquanto encontramos outro escritor.',
  lowActivity: 'Há pouca atividade agora',
  lowActivityBody: 'Continue buscando ou escreva agora e espere outro escritor responder depois.',
  async: 'Escrever e esperar rival',
  cancel: 'Cancelar busca',
  prompt: 'Tema',
  editor: 'Seu relato',
  placeholder: 'A primeira frase espera por você…',
  remaining: 'Tempo restante',
  submit: 'Enviar relato',
  submitting: 'Enviando…',
  minimum: 'Mínimo: 50 caracteres sem espaços.',
  limits: 'Limite do servidor',
  bytes: 'bytes UTF-8',
  characters: 'caracteres',
  saved: 'O texto é salvo neste navegador.',
  saveFailed: 'Não foi possível salvar o texto neste navegador. Copie seu relato antes de sair.',
  frozen: 'Estamos verificando o envio. Você pode tentar novamente com o mesmo texto.',
  pending: 'Seu relato já foi enviado',
  pendingBody: 'Esperamos o rival e o veredito. Volte pelo histórico sem enviar novamente.',
  queued: 'Seu Ranked está esperando',
  queuedBody: 'Outro escritor responderá ao mesmo tema. O duelo e seu resultado aparecerão no histórico quando houver um rival.',
  history: 'Histórico de duelos',
  empty: 'Ainda não há duelos',
  emptyBody: 'Suas partidas aparecerão aqui.',
  historyError: 'Não foi possível carregar o histórico.',
  retry: 'Tentar novamente',
  more: 'Ver mais duelos',
  detail: 'Ver duelo completo',
  private: 'Detalhe privado',
  rival: 'Rival a confirmar',
  won: 'Vitória',
  lost: 'Derrota',
  draw: 'Empate',
  in_progress: 'Em andamento',
  abandoned: 'Abandonado',
  completed: 'Concluído',
  all: 'Todos',
  ranked: 'Ranked',
  asyncRanked: 'Ranked assíncrono',
  practice: 'Prática',
  sprint: 'Solo Sprint',
  challenge: 'Desafio',
  result: 'Resultado do duelo',
  verdict: 'Veredito',
  feedback: 'Para sua escrita',
  winner: 'Vencedor',
  score: 'Pontuação',
  profile: 'Voltar ao perfil',
  another: 'Voltar ao Ranked',
  detailError: 'Este duelo ainda não está disponível ou você não tem acesso.',
  forfeit: 'Desistir',
  forfeitTitle: 'Abandonar o duelo?',
  forfeitBody: 'Conta como uma derrota. Você pode perder pontos de liga e a tinta utilizada não é devolvida.',
  keepWriting: 'Continuar escrevendo',
  expired: 'O tempo de escrita terminou',
  expiredBody: 'Guardamos o texto neste navegador. Você pode copiá-lo antes de continuar.',
  unavailable: 'A escrita não está mais ativa',
  unavailableBody: 'Confira o histórico para verificar se o duelo foi resolvido. Guardamos o texto deste navegador.',
  cancelled: 'A busca terminou',
  finished: 'O veredito está pronto',
  viewResult: 'Ver resultado',
  otherMode: 'Você já tem outra partida em andamento',
  otherModeBody: 'Continue essa partida no aplicativo antes de iniciar Ranked.',
  verification: 'Verifique seu e-mail para jogar Ranked.',
  sendVerification: 'Enviar e-mail de verificação',
  verificationSent: 'E-mail enviado. Após verificar, tente novamente.',
  energy: 'Tinta disponível',
  cost: 'Custo por duelo',
  refill: 'Próxima recarga',
  noEnergy: 'Você não tem tinta suficiente. Espere a próxima recarga.',
  queueList: 'Ranked pendentes',
  matched: 'Rival encontrado',
  expires: 'Disponível até',
  loading: 'Carregando duelos…',
};
export const DUELS_COPY: Record<Locale, Copy> = { es, en, pt };
const errors: Record<Locale, Record<string, string>> = {
  es: {
    generic: 'No se pudo completar la acción. Reintenta para comprobar el estado.',
    network: 'No se pudo conectar. Reintenta para comprobar el estado. Los envíos pendientes usan el mismo texto.',
    forbidden: 'No se pudo iniciar o continuar el duelo. Comprueba tu tinta y los requisitos de Ranked.',
    invalid: 'El relato debe tener al menos 50 caracteres sin espacios y respetar el límite indicado.',
    max_open_ranked_async: 'Ya tienes el máximo de Ranked pendientes. Espera a que se resuelvan.',
    ranked_async_disabled: 'Ranked asíncrono no está disponible ahora.',
    ranked_async_unavailable_language: 'Ranked asíncrono no está disponible para el idioma de tu cuenta.',
    insufficient_energy: es.noEnergy,
    expired: 'El plazo de envío terminó. Conserva una copia de tu relato.',
    session: 'Tu sesión terminó. Vuelve a iniciar sesión.',
    not_found: 'La partida ya no está disponible.',
  },
  en: {
    generic: 'Could not complete the action. Retry to check the current state.',
    network: 'Could not connect. Retry to check the current state. Pending submissions use the same text.',
    forbidden: 'Could not start or continue the duel. Check your ink and Ranked requirements.',
    invalid: 'Your story needs at least 50 non-whitespace characters and must fit the shown limit.',
    max_open_ranked_async: 'You have the maximum number of pending Ranked. Wait for them to resolve.',
    ranked_async_disabled: 'Async Ranked is unavailable right now.',
    ranked_async_unavailable_language: 'Async Ranked is unavailable in your account language.',
    insufficient_energy: en.noEnergy,
    expired: 'The submission deadline passed. Keep a copy of your story.',
    session: 'Your session ended. Sign in again.',
    not_found: 'This match is no longer available.',
  },
  pt: {
    generic: 'Não foi possível concluir a ação. Tente novamente para verificar o estado.',
    network: 'Não foi possível conectar. Tente novamente para verificar o estado. Os envios pendentes usam o mesmo texto.',
    forbidden: 'Não foi possível iniciar ou continuar o duelo. Verifique sua tinta e os requisitos de Ranked.',
    invalid: 'O relato precisa ter ao menos 50 caracteres sem espaços e respeitar o limite indicado.',
    max_open_ranked_async: 'Você já tem o máximo de Ranked pendentes. Espere serem resolvidos.',
    ranked_async_disabled: 'Ranked assíncrono não está disponível agora.',
    ranked_async_unavailable_language: 'Ranked assíncrono não está disponível no idioma da sua conta.',
    insufficient_energy: pt.noEnergy,
    expired: 'O prazo de envio terminou. Guarde uma cópia do seu relato.',
    session: 'Sua sessão terminou. Entre novamente.',
    not_found: 'A partida não está mais disponível.',
  },
};
export function duelErrorMessage(code: string, locale: Locale): string {
  const key = ['draft_deadline_passed', 'draft_not_found'].includes(code)
    ? 'expired'
    : ['story_too_short', 'story_too_long'].includes(code)
      ? 'invalid'
      : code;
  return errors[locale][key] || errors[locale].generic;
}
